apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: superheroe-gokit-api-ing
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: superheroe-gokit-api-svc
          servicePort: 8080
